openapi: "3.0.0"
info:
  version: 1.0.0
  title: Battlefront Companion API
servers:
  - url: http://localhost:3000/api/v1
paths:
  /healthcheck:
    get:
      summary: Healthcheck of API
      tags:
        [ 'healthcheck' ]
      responses:
        '200':
          description: ok
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /hero/all:
    get:
      summary: Get all heroes
      tags:
        [ 'hero/all' ]
      responses:
        '200':
          description: ok
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      required:
        - message
      properties:
        message:
          type: string